language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: IyK3arLyz5a5hX9b/X/khGRSI2Kp2ez9CCAyduu+l20LLE9Hh3bndFLWclw9QIZ0Qo+BU1mdZzcy5L68bWUBCmg4PjxrLG+7SzNP7nf+S1O27OZLoc+SbYA6RgegKl3IUCGhzbHFOHYCdGpMEypTV8+40Cv7WJ3HRhP95PyjgtotL6u6KX5VydbjT/2UL8PgTmSatdob8ULbYg7OJPLae4AQG2lJ29Katy0fXx/z9G1vikMaQXu0KPtEymdx+o1vdOFpur7RjZ66fYIjSN+gBSaC79BryqwvWVsCJHcq5OBzIyU3/iEl4D9vXVi26e8moBHCKMuNe7iQXb65a0NgHim3JCad95aYM0Mzgo3fTe55bPm+Bxa8beA6rtAImnQ1OfurizoMQAlJtuc8/S9t4+Gr7U2tWsM0z+GhKIDeIGVGzCjbCEsSzgOJR1fz7eK5RVV0ovu82kBTI1P+BEtNuvMzwqcyPauCY3pye2e3SvEPuRjVB6aci6TGepWUURuL1/W8/GZ/8Ll1bVJxK0OpC7A9GDHeKpyQ9feMnN6CTEisp5kQl8TopcZjnoKrCLwCxTCvECYA/t+N2rvhBBV+UHvo3svtAEZEiHSBrY0yUZYCGlje5fywPvvun/vFKlm1kHdmNLl80IUrN/4ifyqr76mLmheW8DnFmXVM03KAEPY=
  app: desolate-ravine-54161